export const getImg = (ext) => {
  switch (ext.slice(1)) {
    case "fla":
    case "swf":
      return "actionscript.svg";
    case "bat":
      return "batch.svg";
    case "sh":
      return "bash.svg";
    case "c":
      return "c.svg";
    case "cs":
      return "c#.svg";
    case "cpp":
      return "c++.svg";
    case "clj":
    case "cljs":
    case "cljc":
    case "edn":
      return "clojure.svg";
    case "coffee":
      return "coffeescript.svg";
    case "cfm":
    case "cfc":
      return "coldfusion.svg";
    case "css":
      return "css.svg";
    case "dart":
      return "dart.svg";
    case "":
      return "docker.svg";
    case "erl":
    case "hrl":
      return "erlang.svg";
    case "fs":
      return "f#.svg";
    case "git":
    case "gitignore":
    case "gitinclude":
      return "git.svg";
    case "go":
      return "golang.svg";
    case "graphql":
      return "graphql.svg";
    case "haml":
      return "haml.svg";
    case "hbs":
    case "handlebars":
      return "handlebars.svg";
    case "html":
    case "htm":
      return "html.svg";
    case "ini":
      return "ini.svg";
    case "jar":
    case "java":
      return "java.svg";
    case "js":
      return "javascript.svg";
    case "json":
      return "json.svg";
    case "jsx":
      return "jsx.svg";
    case "less":
      return "less.svg";
    case "lisp":
      return "lisp.svg";
    case "ls":
      return "livescript.svg";
    case "md":
    case "markdown":
      return "markdown.svg";
    case "perl":
      return "perl.svg";
    case "php":
      return "php.svg";
    case "py":
      return "python.svg";
    case "r":
      return "r.svg";
    case "rb":
      return "ruby.svg";
    case "rs":
    case "rlib":
      return "rust.svg";
    case "sass":
    case "scss":
      return "sass.svg";
    case "sc":
    case "scala":
      return "scala.svg";
    case "svg":
      return "svg.svg";
    case "ts":
      return "typescript.svg";
    case "vbs":
      return "vbscript.svg";
    case "vue":
      return "vue.svg";
    case "xml":
      return "xml.svg";
    case "yaml":
      return "yaml";
    case "aql":
    case "mysql":
    case "pgsql":
    case "sql":
      return "db.svg";
    default:
      return "default.svg";
  }
};
