export const getModes = name => {
  switch (name) {
    case 'abap':
      return 'abap'
    case 'abc':
      return 'abc'
    case 'fla':
    case 'swf':
      return 'actionscript'
    case 'ada':
      return 'ada'
    case 'alda':
      return 'alda'
    case 'applescript':
      return 'applescript'
    case 'aql':
      return 'aql'
    case 'ascii':
      return 'ascii'
    case 'asl':
      return 'asl'
    case 'bat':
      return 'batch'
    case 'cpp':
    case 'c':
      return 'c_cpp'
    case 'clj':
    case 'cljs':
    case 'cljc':
    case 'edn':
      return 'clojure'
    case 'cbl':
    case 'cob':
    case 'cpy':
      return 'cobol'
    case 'coffee':
      return 'coffee'
    case 'cfm':
    case 'cfc':
      return 'coldfusion'
    case 'cs':
      return 'csharp'
    case 'csp':
      return 'csp'
    case 'css':
      return 'css'
    case 'dart':
      return 'dart'
    case '':
      return 'dockerfile'
    case 'ejs':
      return 'ejs'
    case 'elm':
      return 'elm'
    case 'erl':
    case 'hrl':
      return 'erlang'
    case 'fs':
      return 'fsharp'
    case 'gitignore':
      return 'gitignore'
    case 'glsl':
      return 'glsl'
    case 'go':
      return 'golang'
    case 'graphql':
      return 'graphqlschema'
    case 'haml':
      return 'haml'
    case 'hbs':
    case 'handlebars':
      return 'handlebars'
    case 'hjson':
      return 'hjson'
    case 'html':
    case 'htm':
      return 'html'
    case 'ini':
      return 'ini'
    case 'io':
      return 'io'
    case 'jack':
      return 'jack'
    case 'jade':
      return 'jade'
    case 'java':
    case 'jar':
      return 'java'
    case 'js':
    case 'vue':
      return 'javascript'
    case 'json':
      return 'json'
    case 'jsp':
      return 'jsp'
    case 'jsx':
      return 'jsx'
    case 'latex':
      return 'latex'
    case 'less':
      return 'less'
    case 'lisp':
      return 'lisp'
    case 'ls':
      return 'livescript'
    case 'lsl':
      return 'lsl'
    case 'lua':
      return 'lua'
    case 'md':
      return 'markdown'
    case 'mysql':
      return 'mysql'
    case 'perl':
      return 'perl'
    case 'pgsql':
      return 'pgsql'
    case 'php':
      return 'php'
    case 'pig':
      return 'pig'
    case 'py':
      return 'python'
    case 'qml':
      return 'qml'
    case 'r':
      return 'r'
    case 'rdoc':
      return 'rdoc'
    case 'red':
      return 'red'
    case 'rhtml':
      return 'rhtml'
    case 'rst':
      return 'rst'
    case 'rb':
      return 'ruby'
    case 'rs':
    case 'rlib':
      return 'rust'
    case 'sass':
      return 'sass'
    case 'scala':
    case 'sc':
      return 'scala'
    case 'scss':
      return 'scss'
    case 'sh':
      return 'sh'
    case 'sjs':
      return 'sjs'
    case 'slim':
      return 'slim'
    case 'sql':
      return 'sql'
    case 'svg':
      return 'svg'
    case 'tex':
      return 'tex'
    case 'txt':
      return 'text'
    case 'tsx':
      return 'tsx'
    case 'twig':
      return 'twig'
    case 'ts':
      return 'typescript'
    case 'vbs':
      return 'vbscript'
    case 'xml':
      return 'xml'
    case 'yaml':
    case 'yml':
      return 'yaml'
    default:
      return 'plain_text'
  }
}
