export const getThemes = name => {
  switch (name) {
    case 'ambiance':
      return 'theme-ambiance'
    case 'chaos':
      return 'theme-chaos'
    case 'chrome':
      return 'theme-chrome'
    case 'clouds_midnight':
      return 'theme-clouds_midnight'
    case 'clouds':
      return 'theme-clouds'
    case 'cobalt':
      return 'theme-cobalt'
    case 'crimson_editor':
      return 'theme-crimson_editor'
    case 'dawn':
      return 'theme-dawn'
    case 'dracula':
      return 'theme-dracula'
    case 'dreamweaver':
      return 'theme-dreamweaver'
    case 'eclipse':
      return 'theme-eclipse'
    case 'github':
      return 'theme-github'
    case 'gob':
      return 'theme-gob'
    case 'gruvbox':
      return 'theme-gruvbox'
    case 'idle_fingers':
      return 'theme-idle_fingers'
    case 'iplastic':
      return 'theme-iplastic'
    case 'katzenmilch':
      return 'theme-katzenmilch'
    case 'kr_theme':
      return 'theme-kr_theme'
    case 'kuroir':
      return 'theme-kuroir'
    case 'merbivore_soft':
      return 'theme-merbivore_soft'
    case 'merbivore':
      return 'theme-merbivore'
    case 'mono_industrial':
      return 'theme-mono_industrial'
    case 'monokai':
      return 'theme-monokai'
    case 'nord_dark':
      return 'theme-nord_dark'
    case 'pastel_on_dark':
      return 'theme-pastel_on_dark'
    case 'solarized_dark':
      return 'theme-solarized_dark'
    case 'solarized_light':
      return 'theme-solarized_light'
    case 'sqlserver':
      return 'theme-sqlserver'
    case 'terminal':
      return 'theme-terminal'
    case 'textmate':
      return 'theme-textmate'
    case 'tomorrow_night_blue':
      return 'theme-tomorrow_night_blue'
    case 'tomorrow_night_bright':
      return 'theme-tomorrow_night_bright'
    case 'tomorrow_night_eighties':
      return 'theme-tomorrow_night_eighties'
    case 'tomorrow_night':
      return 'theme-tomorrow_night'
    case 'tomorrow':
      return 'theme-tomorrow'
    case 'twilight':
      return 'theme-twilight'
    case 'vibrant_ink':
      return 'theme-vibrant_ink'
    case 'xcode':
      return 'theme-xcode'
    default:
  }
}
